name = "edge-rocketseat"
main = "src/index.ts"
compatibility_date = "2022-07-23"

[vars]
UPSTASH_REDIS_REST_URL = "https://global-glowing-chow-30857.upstash.io"

# [secrets] 
# UPSTASH_REDIS_REST_TOKEN